SELECT e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, l.LEAVE_TYPE, l.ESTABLISHED, l.DUE_TO  FROM EMPLOYEE_LEAVE l
  INNER JOIN EMPLOYEE e ON e.ID=l.EMPLOYEE_ID
WHERE e.EMPLOYEE_TYPE='HOURLYPAID' AND e.IS_ACTIVE=1 AND l.IS_ACTIVE=1
ORDER BY e.LAST_NAME, l.DUE_TO


SELECT e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, l.LEAVE_TYPE, l.ESTABLISHED, l.DUE_TO  FROM EMPLOYEE_LEAVE l
  INNER JOIN EMPLOYEE e ON e.ID=l.EMPLOYEE_ID
WHERE (e.EMPLOYEE_TYPE='HOURLYPAID' OR e.EMPLOYEE_TYPE='DEPUTY') 
 AND (l.LEAVE_TYPE='LABOUR_LEAVE' OR l.LEAVE_TYPE='PUERPERIUM_LEAVE' OR l.LEAVE_TYPE='MEDICAL_LABOUR_LEAVE') 
AND l.ESTABLISHED > '20100901'
ORDER BY e.LAST_NAME, l.DUE_TO


SELECT e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, u.TITLE, l.LEAVE_TYPE, l.ESTABLISHED, l.DUE_TO  FROM EMPLOYEE_LEAVE l
  INNER JOIN EMPLOYEE e ON e.ID=l.EMPLOYEE_ID
  INNER JOIN EMPLOYMENT em ON e.CURRENT_EMPLOYMENT_ID=em.ID
  INNER JOIN UNIT u ON u.UNIT_ID=em.SCHOOL_ID
WHERE (e.EMPLOYEE_TYPE='REGULAR') 
 AND (l.LEAVE_TYPE='LABOUR_LEAVE' OR l.LEAVE_TYPE='PUERPERIUM_LEAVE' OR l.LEAVE_TYPE='MEDICAL_LABOUR_LEAVE') 
AND l.DUE_TO > '20100101'
ORDER BY u.TITLE, e.LAST_NAME, l.DUE_TO

SELECT e.ID, e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, u.TITLE, l.LEAVE_TYPE, l.ESTABLISHED, l.DUE_TO  FROM EMPLOYEE_LEAVE l
  INNER JOIN EMPLOYEE e ON e.ID=l.EMPLOYEE_ID
  INNER JOIN EMPLOYMENT em ON e.CURRENT_EMPLOYMENT_ID=em.ID
  INNER JOIN UNIT u ON u.UNIT_ID=em.SCHOOL_ID
WHERE (e.EMPLOYEE_TYPE='REGULAR') 
 AND (l.LEAVE_TYPE='LABOUR_LEAVE' OR l.LEAVE_TYPE='PUERPERIUM_LEAVE' OR l.LEAVE_TYPE='MEDICAL_LABOUR_LEAVE') 
AND l.DUE_TO > '20110201' 
ORDER BY u.TITLE, e.LAST_NAME, l.DUE_TO


