SELECT e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, u.TITLE, le.LEGACY_CODE, le.DESCRIPTION, l.ESTABLISHED, l.DUE_TO FROM EMPLOYEE_LEAVES l
   INNER JOIN EMPLOYEE e ON e.ID=l.EMPLOYEE_ID
   INNER JOIN EMPLOYMENT em ON e.CURRENT_EMPLOYMENT_ID=em.ID
   INNER JOIN UNIT u ON u.UNIT_ID=em.SCHOOL_ID
   INNER JOIN EMPLOYEE_LEAVE_TYPE le ON le.ID=l.EMPLOYEE_LEAVE_TYPE_ID 
      
  WHERE l.ESTABLISHED<='20120901' AND l.DUE_TO>='20120901'
ORDER BY e.LAST_NAME, e.FIRST_NAME


SELECT COUNT(*) FROM EMPLOYEE_LEAVE