SELECT e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, u.TITLE, le.LEGACY_CODE, le.DESCRIPTION, l.ESTABLISHED, l.DUE_TO FROM EMPLOYEE_LEAVES l
   INNER JOIN EMPLOYEE e ON e.ID=l.EMPLOYEE_ID
   INNER JOIN EMPLOYMENT em ON e.CURRENT_EMPLOYMENT_ID=em.ID
   INNER JOIN UNIT u ON u.UNIT_ID=em.SCHOOL_ID
   INNER JOIN EMPLOYEE_LEAVE_TYPE le ON le.ID=l.EMPLOYEE_LEAVE_TYPE_ID 
      
  WHERE l.ESTABLISHED<='20120901' AND l.DUE_TO>='20120901'
ORDER BY e.LAST_NAME, e.FIRST_NAME

SELECT COUNT(*),  lt.DESCRIPTION FROM EMPLOYEE_LEAVES l
    INNER JOIN EMPLOYEE_LEAVE_TYPE lt ON lt.id=l.EMPLOYEE_LEAVE_TYPE_ID
WHERE (lt.LEGACY_CODE='45' OR lt.LEGACY_CODE='46' OR lt.LEGACY_CODE='37' OR lt.LEGACY_CODE='33' OR lt.LEGACY_CODE='34')
AND (l.IS_DELETED IS NULL OR l.IS_DELETED=0)
AND (YEAR(l.ESTABLISHED)=2010 OR (YEAR(l.ESTABLISHED)<2010 AND YEAR(l.DUE_TO)=2010))
    GROUP BY lt.DESCRIPTION


SELECT COUNT(*),  lt.DESCRIPTION FROM EMPLOYEE_LEAVES l
    INNER JOIN EMPLOYEE_LEAVE_TYPE lt ON lt.id=l.EMPLOYEE_LEAVE_TYPE_ID
WHERE (lt.LEGACY_CODE='45' OR lt.LEGACY_CODE='46' OR lt.LEGACY_CODE='37' OR lt.LEGACY_CODE='33' OR lt.LEGACY_CODE='34')
AND (l.IS_DELETED IS NULL OR l.IS_DELETED=0)
AND (YEAR(l.ESTABLISHED)=2013)
    GROUP BY lt.DESCRIPTION


SELECT e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, lt.LEGACY_CODE, lt.DESCRIPTION, l.ESTABLISHED, l.DUE_TO FROM EMPLOYEE_LEAVES l
    INNER JOIN EMPLOYEE_LEAVE_TYPE lt ON lt.id=l.EMPLOYEE_LEAVE_TYPE_ID
    INNER JOIN EMPLOYEE e ON e.ID=l.EMPLOYEE_ID
WHERE (l.IS_DELETED IS NOT NULL OR l.IS_DELETED=0)
    AND (YEAR(l.ESTABLISHED)>=2010 OR YEAR(l.ESTABLISHED)<=2010)
    AND (lt.LEGACY_CODE='41' OR lt.LEGACY_CODE='55' OR lt.LEGACY_CODE='35' OR lt.LEGACY_CODE='45')
    AND e.ID IN (
SELECT e.ID FROM EMPLOYEE_LEAVES l
    INNER JOIN EMPLOYEE_LEAVE_TYPE lt ON lt.id=l.EMPLOYEE_LEAVE_TYPE_ID
    INNER JOIN EMPLOYEE e ON e.ID=l.EMPLOYEE_ID
WHERE lt.LEGACY_CODE='45'
    AND (l.IS_DELETED IS NOT NULL OR l.IS_DELETED=0)
    AND (YEAR(l.ESTABLISHED)>=2010 OR YEAR(l.ESTABLISHED)<=2010)
) ORDER BY e.ID, l.ESTABLISHED



SELECT e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, lt.LEGACY_CODE, lt.DESCRIPTION, l.ESTABLISHED, l.DUE_TO FROM EMPLOYEE_LEAVES l
    INNER JOIN EMPLOYEE_LEAVE_TYPE lt ON lt.id=l.EMPLOYEE_LEAVE_TYPE_ID
    INNER JOIN EMPLOYEE e ON e.ID=l.EMPLOYEE_ID
WHERE (l.IS_DELETED IS NULL OR l.IS_DELETED=0)
    AND (YEAR(l.ESTABLISHED)<=2010 AND YEAR(l.DUE_TO)>=2009)
    AND (lt.LEGACY_CODE='41' OR lt.LEGACY_CODE='55' OR lt.LEGACY_CODE='35' OR lt.LEGACY_CODE='45')
    AND e.ID IN (
SELECT e.ID FROM EMPLOYEE_LEAVES l
    INNER JOIN EMPLOYEE_LEAVE_TYPE lt ON lt.id=l.EMPLOYEE_LEAVE_TYPE_ID
    INNER JOIN EMPLOYEE e ON e.ID=l.EMPLOYEE_ID
WHERE lt.LEGACY_CODE='45'
    AND (l.IS_DELETED IS  NULL OR l.IS_DELETED=0)
    AND (YEAR(l.ESTABLISHED)=2010 OR (YEAR(l.ESTABLISHED)<2010 AND YEAR(l.DUE_TO)=2010))
) ORDER BY e.ID, l.ESTABLISHED


SELECT e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, lt.LEGACY_CODE, lt.DESCRIPTION, l.ESTABLISHED, l.DUE_TO FROM EMPLOYEE_LEAVES l
    INNER JOIN EMPLOYEE_LEAVE_TYPE lt ON lt.id=l.EMPLOYEE_LEAVE_TYPE_ID
    INNER JOIN EMPLOYEE e ON e.ID=l.EMPLOYEE_ID
WHERE (l.IS_DELETED IS NULL OR l.IS_DELETED=0)
    AND (YEAR(l.ESTABLISHED)<=2013 AND YEAR(l.DUE_TO)>=2012)
    AND (lt.LEGACY_CODE='41' OR lt.LEGACY_CODE='55' OR lt.LEGACY_CODE='35' OR lt.LEGACY_CODE='45')
    AND e.ID IN (
SELECT e.ID FROM EMPLOYEE_LEAVES l
    INNER JOIN EMPLOYEE_LEAVE_TYPE lt ON lt.id=l.EMPLOYEE_LEAVE_TYPE_ID
    INNER JOIN EMPLOYEE e ON e.ID=l.EMPLOYEE_ID
WHERE lt.LEGACY_CODE='45'
    AND (l.IS_DELETED IS NULL OR l.IS_DELETED=0)
    AND (YEAR(l.ESTABLISHED)=2013)
) ORDER BY e.ID, l.ESTABLISHED



SELECT * FROM EMPLOYEE_LEAVE_TYPE lt
    WHERE lt.LEGACY_CODE='45'
























