SELECT e.LAST_NAME AS '???????', e.FIRST_NAME AS '?????', sp.SPECIALIZATION_ID, sp.TITLE, lt.DESCRIPTION AS '?????????', l.COMMENT AS '??????', convert(varchar, l.ESTABLISHED, 103) AS '??????', convert(varchar, l.DUE_TO, 103) AS '????' FROM EMPLOYEE_LEAVES l 
 INNER JOIN EMPLOYEE e ON l.EMPLOYEE_ID=e.ID
 INNER JOIN EMPLOYEE_LEAVE_TYPE lt ON l.EMPLOYEE_LEAVE_TYPE_ID= lt.ID
 INNER JOIN SPECIALIZATION sp ON sp.SPECIALIZATION_ID=e.LAST_SPECIALIZATION_ID
WHERE (l.IS_AUTOCANCELED=0 OR l.IS_AUTOCANCELED IS NULL) 
    AND (l.IS_DELETED = 0 OR l.IS_DELETED IS NULL)
    AND l.DUE_TO >= '20130930'
   ORDER BY sp.SPECIALIZATION_ID, e.LAST_NAME


