SELECT e.LAST_NAME, e.FIRST_NAME,s.SPECIALIZATION_ID, u.TITLE, l.LEAVE_TYPE,l.ESTABLISHED, l.DUE_TO FROM EMPLOYEE_LEAVE l 
    INNER JOIN EMPLOYEE e ON l.EMPLOYEE_ID=e.ID
    INNER JOIN SPECIALIZATION s ON e.LAST_SPECIALIZATION_ID = s.SPECIALIZATION_ID
    INNER JOIN EMPLOYMENT em ON e.CURRENT_EMPLOYMENT_ID=em.ID
    INNER JOIN UNIT u ON u.UNIT_ID=em.SCHOOL_ID
WHERE l.IS_ACTIVE = 1
    AND l.ESTABLISHED < '2010-09-02'
    AND l.DUE_TO > '2010-09-02'
ORDER BY s.SPECIALIZATION_ID, l.LEAVE_TYPE, e.LAST_NAME


# ΕΝΕΡΓΕΣ ΑΔΕΙΕΣ ΑΝΑ ΕΙΔΙΚΟΤΗΤΑ ΑΝΑ ΠΕΡΙΟΧΗ

SELECT em.SPECIALIZATION_ID AS 'ΕΙΔΙΚΟΤΗΤΑ', COUNT(l.ID) AS 'ΠΛΗΘΟΣ' FROM EMPLOYEE_LEAVE l 
    INNER JOIN EMPLOYEE e ON l.EMPLOYEE_ID=e.ID
    INNER JOIN SPECIALIZATION s ON e.LAST_SPECIALIZATION_ID = s.SPECIALIZATION_ID
    INNER JOIN EMPLOYMENT em ON e.CURRENT_EMPLOYMENT_ID=em.ID
    INNER JOIN UNIT u ON u.UNIT_ID=em.SCHOOL_ID
    INNER JOIN SCHOOL sc ON sc.UNIT_ID = u.UNIT_ID
 WHERE l.IS_ACTIVE = 1 
    AND em.SPECIALIZATION_ID IN (SELECT  s.SPECIALIZATION_ID FROM SPECIALIZATION s)
    AND sc.REGION='Β'
  GROUP BY em.SPECIALIZATION_ID
  ORDER BY  em.SPECIALIZATION_ID