// ΑΡΙΘΜΟΣ ΔΙΔΑΚΤΙΚΩΝ ΩΡΩΝ ΕΚΠΑΙΔΕΥΤΙΚΟΥ ΑΝΑ ΜΟΝΑΔΑ
SELECT c.UNIT_ID, SUM(c.HOURS) FROM TEACHING_HOUR_CDR c 
WHERE
    c.EMPLOYEE_ID=9281
AND c.SCHOOL_YEAR_ID=10
GROUP BY c.UNIT_ID

// ΑΡΙΘΜΟΣ ΔΙΔΑΚΤΙΚΩΝ ΩΡΩΝ ΕΚΠΑΙΔΕΥΤΙΚΟΥ ΑΝΑ ΜΟΝΑΔΑ
SELECT c.UNIT_ID, u.TITLE, SUM(c.HOURS) FROM TEACHING_HOUR_CDR c 
    INNER JOIN UNIT u ON u.UNIT_ID=c.UNIT_ID
WHERE
    c.EMPLOYEE_ID=9281 AND c.SCHOOL_YEAR_ID=10
GROUP BY c.UNIT_ID, u.TITLE


// ΑΡΙΘΜΟΣ ΩΡΩΝ ΑΝΑ ΕΚΠΑΙΔΕΥΤΙΚΟ
SELECT c.EMPLOYEE_ID, SUM(c.HOURS) FROM TEACHING_HOUR_CDR c 
WHERE
   c.SCHOOL_YEAR_ID=11
GROUP BY c.EMPLOYEE_ID


SELECT c.EMPLOYEE_ID, SUM(c.HOURS) FROM TEACHING_HOUR_CDR c 
WHERE
   c.SCHOOL_YEAR_ID=11
GROUP BY c.EMPLOYEE_ID
HAVING SUM(c.HOURS) < 0



SELECT * FROM TEACHING_HOUR_CDR c WHERE 
    c.SPECIALIZATION_ID IS NULL AND
    c.SCHOOL_YEAR_ID=10


SELECT * FROM SCHOOL_YEAR


SELECT * FROM TEACHING_HOUR_CDR c WHERE 
    c.CDR_TYPE = 'LEAVE' AND
    c.SCHOOL_YEAR_ID=10
    c.EMPLOYEE_ID=10403

SELECT * FROM TEACHING_HOUR_CDR c WHERE
    c.EMPLOYEE_ID=10403
AND
    c.SCHOOL_YEAR_ID=10


SELECT * FROM TEACHING_HOUR_CDR c WHERE
    c.EMPLOYEE_ID=10403
AND c.SCHOOL_YEAR_ID=10

SELECT c.UNIT_ID, MAX(u.TITLE), SUM(c.HOURS) FROM TEACHING_HOUR_CDR c
INNER JOIN UNIT u ON u.UNIT_ID=c.UNIT_ID
 WHERE
c.SPECIALIZATION_ID='ΠΕ1901'
AND c.SCHOOL_YEAR_ID=10
GROUP BY(c.UNIT_ID)
ORDER BY(u.TITLE) 

ORDER BY c.COMMENT
SELECT * FROM TEACHING_HOUR_CDR c 



SELECT * FROM SCHOOL_YEAR



SELECT * FROM EMPLOYEE e WHERE e.LAST_NAME = 'ΣΛΑΒΙΚ'