// ΑΡΙΘΜΟΣ ΔΙΔΑΚΤΙΚΩΝ ΩΡΩΝ ΕΚΠΑΙΔΕΥΤΙΚΟΥ ΑΝΑ ΜΟΝΑΔΑ
SELECT c.UNIT_ID, SUM(c.HOURS) FROM TEACHING_HOUR_CDR c 
WHERE
    c.EMPLOYEE_ID=9281
AND c.SCHOOL_YEAR_ID=10
GROUP BY c.UNIT_ID

// ΑΡΙΘΜΟΣ ΔΙΔΑΚΤΙΚΩΝ ΩΡΩΝ ΕΚΠΑΙΔΕΥΤΙΚΟΥ ΑΝΑ ΜΟΝΑΔΑ
SELECT c.UNIT_ID, u.TITLE, SUM(c.HOURS) FROM TEACHING_HOUR_CDR c 
    INNER JOIN UNIT u ON u.UNIT_ID=c.UNIT_ID
WHERE
    c.EMPLOYEE_ID=9281 AND c.SCHOOL_YEAR_ID=10
GROUP BY c.UNIT_ID, u.TITLE


SELECT * FROM TEACHING_HOUR_CDR c WHERE 
    c.SPECIALIZATION_ID IS NULL AND
    c.SCHOOL_YEAR_ID=10


SELECT * FROM SCHOOL_YEAR


SELECT * FROM TEACHING_HOUR_CDR c WHERE 
    c.CDR_TYPE = 'LEAVE' AND
    c.SCHOOL_YEAR_ID=10
    c.EMPLOYEE_ID=10403

SELECT * FROM TEACHING_HOUR_CDR c WHERE
    c.EMPLOYEE_ID=10403
AND
    c.SCHOOL_YEAR_ID=10


SELECT * FROM TEACHING_HOUR_CDR c WHERE
    c.EMPLOYEE_ID=10403
AND c.SCHOOL_YEAR_ID=10

SELECT SUM(c.HOURS) FROM TEACHING_HOUR_CDR c WHERE
    c.EMPLOYEE_ID=10403
AND c.SCHOOL_YEAR_ID=10
AND c.UNIT_ID=999






SELECT * FROM EMPLOYEE e WHERE e.LAST_NAME = 'ΣΛΑΒΙΚ'