SELECT * FROM TEACHING_REQUIREMENT

SELECT * FROM UNIT
SELECT * FROM SCHOOL
SELECT * FROM ORGANIZATIONAL_OFFICE

SELECT * FROM EMPLOYMENT em
    INNER JOIN SCHOOL s ON em.SCHOOL_ID=s.UNIT_ID
    INNER JOIN UNIT u ON s.UNIT_ID=u.UNIT_ID
    INNER JOIN EMPLOYEE e ON e.ID=em.EMPLOYEE_ID
WHERE u.OFFICE_ID=2
    AND em.IS_ACTIVE =1 
    AND em.EMPLOYMENT_TYPE='REGULAR'
    AND e.IS_ACTIVE = 1