SELECT e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, sp.SPECIALIZATION_ID, sp.TITLE, u.TITLE FROM EMPLOYMENT em
    INNER JOIN SCHOOL s ON em.SCHOOL_ID=s.UNIT_ID
    INNER JOIN UNIT u ON s.UNIT_ID=u.UNIT_ID
    INNER JOIN EMPLOYEE e ON e.ID=em.EMPLOYEE_ID
    INNER JOIN SPECIALIZATION sp ON em.SPECIALIZATION_ID=sp.SPECIALIZATION_ID
WHERE em.SCHOOL_YEAR_ID=9
    AND em.IS_ACTIVE =1 
    AND em.EMPLOYMENT_TYPE='REGULAR'
    AND e.IS_ACTIVE = 1
    AND em.SPECIALIZATION_ID LIKE '%ΠΕ1401%'
ORDER BY e.LAST_NAME, e.FIRST_NAME

SELECT e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, sp.SPECIALIZATION_ID, sp.TITLE, u.TITLE FROM EMPLOYMENT em
    INNER JOIN SCHOOL s ON em.SCHOOL_ID=s.UNIT_ID
    INNER JOIN UNIT u ON s.UNIT_ID=u.UNIT_ID
    INNER JOIN EMPLOYEE e ON e.ID=em.EMPLOYEE_ID
    INNER JOIN SPECIALIZATION sp ON em.SPECIALIZATION_ID=sp.SPECIALIZATION_ID
WHERE em.SCHOOL_YEAR_ID=9
    AND em.IS_ACTIVE =1 
    AND em.EMPLOYMENT_TYPE='REGULAR'
    AND e.IS_ACTIVE = 1
    AND em.SPECIALIZATION_ID LIKE '%ΠΕ1807%'
ORDER BY e.LAST_NAME, e.FIRST_NAME

SELECT e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, sp.SPECIALIZATION_ID, sp.TITLE, u.TITLE FROM EMPLOYMENT em
    INNER JOIN SCHOOL s ON em.SCHOOL_ID=s.UNIT_ID
    INNER JOIN UNIT u ON s.UNIT_ID=u.UNIT_ID
    INNER JOIN EMPLOYEE e ON e.ID=em.EMPLOYEE_ID
    INNER JOIN SPECIALIZATION sp ON em.SPECIALIZATION_ID=sp.SPECIALIZATION_ID
WHERE em.SCHOOL_YEAR_ID=11
    AND em.IS_ACTIVE =1 
    AND em.EMPLOYMENT_TYPE='REGULAR'
    AND e.IS_ACTIVE = 1
    AND (em.SPECIALIZATION_ID LIKE '??09%' OR  em.SPECIALIZATION_ID LIKE '??1802%' OR em.SPECIALIZATION_ID LIKE '??1803%' OR em.SPECIALIZATION_ID LIKE '??1810%' OR em.SPECIALIZATION_ID LIKE '??1835%')
ORDER BY e.LAST_NAME, e.FIRST_NAME


SELECT * FROM SCHOOL_YEAR
