SELECT e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, sp.SPECIALIZATION_ID, sp.TITLE, u.TITLE FROM EMPLOYMENT em
    INNER JOIN SCHOOL s ON em.SCHOOL_ID=s.UNIT_ID
    INNER JOIN UNIT u ON s.UNIT_ID=u.UNIT_ID
    INNER JOIN EMPLOYEE e ON e.ID=em.EMPLOYEE_ID
    INNER JOIN SPECIALIZATION sp ON em.SPECIALIZATION_ID=sp.SPECIALIZATION_ID
WHERE em.SCHOOL_YEAR_ID=12
    AND em.IS_ACTIVE =1 
    AND em.EMPLOYMENT_TYPE='REGULAR'
    AND e.IS_ACTIVE = 1
    AND em.SPECIALIZATION_ID LIKE '%ΠΕ0501%'
ORDER BY e.LAST_NAME, e.FIRST_NAME



SELECT e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, sp.SPECIALIZATION_ID, sp.TITLE, u.TITLE FROM EMPLOYMENT em
    INNER JOIN SCHOOL s ON em.SCHOOL_ID=s.UNIT_ID
    INNER JOIN UNIT u ON s.UNIT_ID=u.UNIT_ID
    INNER JOIN EMPLOYEE e ON e.ID=em.EMPLOYEE_ID
    INNER JOIN SPECIALIZATION sp ON em.SPECIALIZATION_ID=sp.SPECIALIZATION_ID
WHERE em.SCHOOL_YEAR_ID=9
    AND em.IS_ACTIVE =1 
    AND em.EMPLOYMENT_TYPE='REGULAR'
    AND e.IS_ACTIVE = 1
    AND em.SPECIALIZATION_ID LIKE '%ΠΕ1807%'
ORDER BY e.LAST_NAME, e.FIRST_NAME

SELECT e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, sp.SPECIALIZATION_ID, sp.TITLE, u.TITLE FROM EMPLOYMENT em
    INNER JOIN SCHOOL s ON em.SCHOOL_ID=s.UNIT_ID
    INNER JOIN UNIT u ON s.UNIT_ID=u.UNIT_ID
    INNER JOIN EMPLOYEE e ON e.ID=em.EMPLOYEE_ID
    INNER JOIN SPECIALIZATION sp ON em.SPECIALIZATION_ID=sp.SPECIALIZATION_ID
WHERE em.SCHOOL_YEAR_ID=12
    AND em.IS_ACTIVE =1 
    AND em.EMPLOYMENT_TYPE='REGULAR'
    AND e.IS_ACTIVE = 1
    AND (em.SPECIALIZATION_ID LIKE 'ΠΕ12%' OR  em.SPECIALIZATION_ID LIKE 'ΠΕ14%' 
        OR em.SPECIALIZATION_ID LIKE 'ΠΕ17%' OR em.SPECIALIZATION_ID LIKE 'ΠΕ18%' 
        OR em.SPECIALIZATION_ID LIKE 'ΠΕ19%' OR em.SPECIALIZATION_ID LIKE 'ΠΕ20%')
ORDER BY e.LAST_NAME, e.FIRST_NAME


SELECT * FROM SCHOOL_YEAR

SELECT * FROM SPECIALIZATION
