SELECT COUNT(*) FROM EMPLOYEE_LEAVES l 
    INNER JOIN EMPLOYEE e ON e.ID=l.EMPLOYEE_ID
    INNER JOIN EMPLOYEE_LEAVE_TYPE lt ON lt.ID=l.EMPLOYEE_LEAVE_TYPE_ID
    INNER JOIN mkdb..bohu b ON (b.KVD=e.LEGACY_CODE AND b.APO=l.ESTABLISHED AND b.EVS=l.DUE_TO)
    INNER JOIN mkdb..basiko ba ON ba.KVD=b.KVD
WHERE (l.INSERTED_ON IS NULL AND l.INSERTED_BY_ID IS NULL) AND b.CODE <> lt.LEGACY_CODE


BEGIN TRAN
DELETE EMPLOYEE_LEAVES WHERE ID IN (
SELECT l.ID FROM EMPLOYEE_LEAVES l 
    INNER JOIN EMPLOYEE e ON e.ID=l.EMPLOYEE_ID
    INNER JOIN EMPLOYEE_LEAVE_TYPE lt ON lt.ID=l.EMPLOYEE_LEAVE_TYPE_ID
    INNER JOIN mkdb..bohu b ON (b.KVD=e.LEGACY_CODE AND b.APO=l.ESTABLISHED AND b.EVS=l.DUE_TO)
    INNER JOIN mkdb..basiko ba ON ba.KVD=b.KVD
WHERE (l.INSERTED_ON IS NULL AND l.INSERTED_BY_ID IS NULL) AND b.CODE <> lt.LEGACY_CODE
)
COMMIT TRAN


SELECT COUNT(*) FROM EMPLOYEE_LEAVES l WHERE l.IMPORTED_ON IS NOT NULL
 
SELECT COUNT(*) FROM EMPLOYEE_LEAVES l WHERE l.IMPORTED_ON IS NULL

SELECT * FROM EMPLOYEE_LEAVES l WHERE l.IMPORTED_ON IS NOT NULL

SELECT * FROM EMPLOYEE e WHERE e.iD=6413