SELECT COUNT(*) FROM EMPLOYMENT em 
    INNER JOIN SCHOOL s ON em.SCHOOL_ID=s.UNIT_ID
    WHERE em.EMPLOYMENT_TYPE='REGULAR' 
        AND s.REGION='Α'
        AND em.IS_ACTIVE =1

SELECT COUNT(*) FROM EMPLOYMENT em 
    INNER JOIN SCHOOL s ON em.SCHOOL_ID=s.UNIT_ID
    WHERE em.EMPLOYMENT_TYPE='REGULAR' 
        AND em.IS_ACTIVE =1



SELECT * FROM WORK_EXPERIENCE_TYPE



SELECT e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, sp.SPECIALIZATION_ID, sp.TITLE, u.TITLE FROM EMPLOYEE e
    INNER JOIN EMPLOYMENT em ON em.EMPLOYEE_ID=e.ID
    INNER JOIN UNIT u ON em.SCHOOL_ID=u.UNIT_ID
    INNER JOIN SPECIALIZATION sp ON em.SPECIALIZATION_ID=sp.SPECIALIZATION_ID
WHERE e.IS_ACTIVE = 1 AND em.IS_ACTIVE = 1 AND em.EMPLOYMENT_TYPE='REGULAR' 
    AND e.ID NOT IN (
        SELECT e.ID FROM SECONDMENT sec
            INNER JOIN EMPLOYEE e ON sec.EMPLOYEE_ID=e.ID
        WHERE sec.IS_ACTIVE = 1 
       AND (sec.ESTABLISHED <= '2009-10-29' AND sec.DUE_TO >= '2009-10-29')
    )
ORDER BY e.LAST_NAME, e.FIRST_NAME


SELECT e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, sp.SPECIALIZATION_ID, sp.TITLE, u.TITLE FROM SECONDMENT sec
    INNER JOIN EMPLOYEE e ON sec.EMPLOYEE_ID=e.ID
    INNER JOIN UNIT u ON sec.TARGET_UNIT_ID=u.UNIT_ID
    INNER JOIN SPECIALIZATION sp ON e.LAST_SPECIALIZATION_ID=sp.SPECIALIZATION_ID
WHERE sec.IS_ACTIVE = 1 
    AND (sec.ESTABLISHED <= '2009-10-29' AND sec.DUE_TO >= '2009-10-29')
    AND sec.SECONDMENT_TYPE='FULL_TO_SCHOOL'
ORDER BY e.LAST_NAME, e.FIRST_NAME


SELECT e.LAST_NAME, e.FIRST_NAME, e.LAST_SPECIALIZATION_ID, su.TITLE, tu.TITLE FROM SECONDMENT s
   INNER JOIN EMPLOYEE e ON e.ID=s.EMPLOYEE_ID
   INNER JOIN UNIT su ON su.UNIT_ID=s.SOURCE_UNIT_ID
   INNER JOIN UNIT tu ON tu.UNIT_ID=s.TARGET_UNIT_ID
WHERE s.SOURCE_PYSDE_ID !=1 AND s.IS_ACTIVE=1
    ORDER BY e.LAST_NAME, e.FIRST_NAME
    

GROUP BY SECONDMENT_TYPE




    INNER JOIN SPECIALIZATION sp ON em.SPECIALIZATION_ID=sp.SPECIALIZATION_ID



SELECT * FROM EMPLOYMENT



SELECT * FROM EMPLOYEE_LEAVE


SELECT * FROM minoas..EMPLOYMENT WHERE EMPLOYMENT_TYPE='HOURLYBASED'
SELECT * FROM minoas..EMPLOYEE WHERE EMPLOYEE_TYPE='HOURLYPAID'


SELECT * FROM minoas..EMPLOYMENT WHERE EMPLOYMENT_TYPE='HOURLYBASED'





SELECT * FROM SPECIALIZATION


SELECT * FROM minoas..EMPLOYEE WHERE LAST_NAME LIKE '%ΠΛΑΤΑ%'
SELECT * FROM minoas..EMPLOYMENT WHERE ID=8216


7549
UPDATE minoas..EMPLOYEE SET IS_ACTIVE=0 WHERE ID=7549


UPDATE minoas..EMPLOYEE SET LAST_SPECIALIZATION_ID='ΠΕ0201' WHERE ID=6256
UPDATE minoas..EMPLOYMENT SET SPECIALIZATION_ID='ΠΕ0201', SCHOOL_ID='059' WHERE ID=8216



SELECT * FROM minoas..EMPLOYMENT WHERE ID=9146

UPDATE EMPLOYMENT SET SCHOOL_ID=232
    WHERE ID=9146

SELECT * FROM minoas..UNIT WHERE TITLE LIKE '%ΕΥΡ%'
SELECT * FROM minoas..SECONDMENT_UNIT WHERE UNIT_ID='1003'

232

UPDATE UNIT SET TITLE='1ο ΣΕΚ ΗΡΑΚΛΕΙΟΥ' WHERE UNIT_ID='410'


SELECT * FROM UNIT u WHERE u.TITLE LIKE '%ΕΠΟ%'


UPDATE minoas..EMPLOYEE SET IS_ACTIVE = 1
UPDATE minoas..EMPLOYMENT SET IS_ACTIVE = 0\




UPDATE SECONDMENT SET EMPLOYEE_REQUESTED=1 

UPDATE SECONDMENT SET SECONDMENT_TYPE=(
SELECT u.SECONDMENT_TYPE FROM SECONDMENT_UNIT u WHERE TARGET_UNIT_ID=u.UNIT_ID)

SELECT * FROM mkdb..basiko WHERE EPIUETO='ΓΕΛΑΣΑΚΗΣ'
SELECT * FROM mkdb..basiko WHERE ANHKEI_ID='9'

SELECT * FROM minoas..EMPLOYEE WHERE LAST_NAME='ΓΕΛΑΣΑΚΗΣ'





UPDATE minoas..MINOAS_EMPLOYMENT SET MANDATORY_WORK_HRS=21, FINAL_WORKING_HOURS=21
select * FROM  minoas..MINOAS_EMPLOYMENT


SELECT * FROM minoas..UNIT u WHERE u.title LIKE '%ΕΕΕΚ%'

UPDATE minoas..UNIT SET TITLE='ΓΛ 8ο ΗΡΑΚΛΕΙΟΥ (ΤΜΗΜΑ ΕΝΤΑΞΗΣ - ΠΡΟΒΛΗΜΑΤΑ ΟΡΑΣΗΣ)', version=1 
    WHERE UNIT_ID='246'

 






SELECT * FROM MINOAS_SCHOOL_YEAR

SELECT * FROM MINOAS_SECONDMENT
SELECT * FROM MINOAS_EMPLOYMENT WHERE EMPLOYMENT_ID=11495

SELECT * FROM minoas..EMPLOYMENT 

DELETE FROM MI
NOAS_SECONDMENT

SELECT * FROM UNIT WHERE TITLE LIKE '%ΒΙΒ%'


SELECT * FROM SECONDMENT_UNIT WHERE UNIT_ID LIKE'%078%'
UPDATE minoas..MINOAS_UNIT SET PYSDE_ID=1

select * from minoas..MINOAS_EMPLOYEE

select * from minoas..MINOAS_EMPLOYMENT

select * from mkdb..basiko

SELECT * FROM mkdb..PR_ANAPL WHERE KVD='401631'

SELECT * FROM mkdb..PR_ANAPL_B WHERE KVD='401631'

SELECT * FROM mkdb..PR_ANAPL_B WHERE SXOL_ETOS='2007-2008'


SELECT (SELECT c.ID FROM minoas..MINOAS_UNIT_CATEGORY c WHERE TITLE='ΣΧΟΛΙΚΗ ΜΟΝΑΔΑ'), u.UNIT_ID FROM minoas..MINOAS_UNIT u WHERE (TITLE LIKE 'ΓΥ%' OR TITLE LIKE 'ΓΛ%' OR TITLE LIKE 'ΕΠΑ%')

SELECT * FROM minoas..MINOAS_UNIT_GATEGORIES

INSERT INTO minoas..MINOAS_UNIT_GATEGORIES(CATEGORY_ID, UNIT_ID) 
    SELECT (SELECT c.ID FROM minoas..MINOAS_UNIT_CATEGORY c WHERE TITLE='ΣΧΟΛΙΚΗ ΜΟΝΑΔΑ'), u.UNIT_ID FROM minoas..MINOAS_UNIT u WHERE (TITLE LIKE 'ΓΥ%' OR TITLE LIKE 'ΓΛ%' OR TITLE LIKE 'ΕΠΑ%')



SELECT c.ID FROM minoas..MINOAS_UNIT_CATEGORY c WHERE TITLE='ΣΧΟΛΙΚΗ ΜΟΝΑΔΑ'
SELECT * FROM minoas..MINOAS_UNIT_CATEGORY

DELETE FROM minoas..MINOAS_UNIT_CATEGORY


SELECT * FROM minoas..MINOAS_SECONDMENT_TYPE

SET IDENTITY_INSERT minoas..MINOAS_SECONDMENT_TYPE ON
INSERT INTO minoas..MINOAS_SECONDMENT_TYPE(ID,TITLE) VALUES(1,'ΣΕ ΣΧΟΛΙΚΗ ΜΟΝΑΔΑ')
INSERT INTO minoas..MINOAS_SECONDMENT_TYPE(ID,TITLE) VALUES(2,'ΣΕ ΓΡΑΦΕΙΑ ΚΑΙ ΔΙΕΥΘΥΝΣΕΙΣ')
INSERT INTO minoas..MINOAS_SECONDMENT_TYPE(ID,TITLE) VALUES(3,'ΣΕ ΒΙΒΛΙΟΘΗΚΗ')
INSERT INTO minoas..MINOAS_SECONDMENT_TYPE(ID,TITLE) VALUES(4,'ΕΚΤΟΣ ΠΥΣΔΕ')
INSERT INTO minoas..MINOAS_SECONDMENT_TYPE(ID,TITLE) VALUES(5,'ΣΕ ΚΕΝΤΡΙΚΗ ΥΠΗΡΕΣΙΑ ΤΟΥ ΥΠΕΠΘ ')
INSERT INTO minoas..MINOAS_SECONDMENT_TYPE(ID,TITLE) VALUES(6,'ΣΕ ΑΕΙ - ΤΕΙ - ΑΣΠΕΤΕ')
INSERT INTO minoas..MINOAS_SECONDMENT_TYPE(ID,TITLE) VALUES(7,'ΣΕ ΜΗΤΡΟΠΟΛΕΙΣ - ΕΚΚΛ. ΣΧΟΛΕΣ')
INSERT INTO minoas..MINOAS_SECONDMENT_TYPE(ID,TITLE) VALUES(8,'ΣΕ ΣΧΟΛΕΙΑ ΔΕΥΤΕΡΗΣ ΕΥΚΑΙΡΙΑΣ')
INSERT INTO minoas..MINOAS_SECONDMENT_TYPE(ID,TITLE) VALUES(9,'ΣΕ ΓΡΑΦΕΙΑ ΒΟΥΛΕΥΤΩΝ')
SET IDENTITY_INSERT minoas..MINOAS_SECONDMENT_TYPE OFF

SELECT * FROM minoas..MINOAS_SECONDMENT_TYPE_UNIT_CATEGORIES

INSERT INTO minoas..MINOAS_SECONDMENT_TYPE_UNIT_CATEGORIES(SECONDMENT_TYPE_ID, UNIT_CATEGORY_ID) VALUES(1,1)
DELETE FROM minoas..MINOAS_SECONDMENT_TYPE

SET IDENTITY_INSERT minoas..MINOAS_UNIT_CATEGORY ON 
INSERT INTO minoas..MINOAS_UNIT_CATEGORY(ID,TITLE) VALUES(1,'ΣΧΟΛΙΚΗ ΜΟΝΑΔΑ')
INSERT INTO minoas..MINOAS_UNIT_CATEGORY(ID,TITLE) VALUES(2,'Δ/ΝΣΗ Δ/ΘΜΙΑΣ ΕΚΠ/ΣΗΣ')
SET IDENTITY_INSERT minoas..MINOAS_UNIT_CATEGORY OFF

SELECT KVD, (KVD+'SS'),EPIUETO FROM mkdb..PR_ANAPL a WHERE a.EIDIK IN (SELECT e.EID FROM mkdb..EIDIK e)


insert into minoas..MINOAS_EMPLOYEE(FIRST_NAME, LAST_NAME,LEGACY_CODE, SPECIALIZATION_ID) values ('FILIPPOS', 'SLAVIKOS', '11122', 'ΠΕ1901')
go

begin tran
INSERT minoas..MINOAS_EMPLOYEE(LEGACY_CODE, FIRST_NAME,LAST_NAME,FATHER_NAME, MOTHER_NAME, BIRTH_DAY, VAT_NUMBER,SPECIALIZATION_ID) 
    SELECT KVD, ONOMA, EPIUETO, PATERAS, ON_MHTROS, DGEN, AFM,EIDKLAD FROM mkdb..basiko

INSERT minoas..MINOAS_EMPLOYEE_REGULAR(EMPLOYEE_ID) SELECT EMPLOYEE_ID FROM minoas..MINOAS_EMPLOYEE

UPDATE minoas..MINOAS_EMPLOYEE_REGULAR 
    SET APPOINTMENT_GOF=b.FEK FROM mkdb..basiko b, minoas..MINOAS_EMPLOYEE_REGULAR m WHERE m.EMPLOYEE_ID 
commit
go

INSERT minoas..MINOAS_EMPLOYEE(LEGACY_CODE, FIRST_NAME,LAST_NAME,FATHER_NAME, SPECIALIZATION_ID)
    SELECT ('ANA_'+KVD), ONOMA, EPIUETO, PATERAS, EIDIK FROM mkdb..PR_ANAPL a WHERE a.EIDIK IN (SELECT e.EID FROM mkdb..EIDIK e)

INSERT minoas..MINOAS_EMPLOYEE_DEPUTY
    SELECT e.EMPLOYEE_ID FROM minoas..MINOAS_EMPLOYEE e INNER JOIN mkdb..PR_ANAPL a ON e.LEGACY_CODE COLLATE DATABASE_DEFAULT='ANA_'+a.KVD COLLATE DATABASE_DEFAULT


SELECT e.EMPLOYEE_ID FROM minoas..MINOAS_EMPLOYEE e INNER JOIN mkdb..PR_ANAPL a ON e.LEGACY_CODE COLLATE DATABASE_DEFAULT='ANA_'+a.KVD COLLATE DATABASE_DEFAULT 

SELECT e.EMPLOYEE_ID, e.LEGACY_CODE, b.KVD, (SELECT s.id FROM minoas..MINOAS_SCHOOL_YEAR s WHERE s.IS_CURRENT_YEAR=1) FROM minoas..MINOAS_EMPLOYEE e INNER JOIN mkdb..basiko b on e.LEGACY_CODE COLLATE DATABASE_DEFAULT
=b.KVD COLLATE DATABASE_DEFAULT



INSERT minoas..MINOAS_EMPLOYMENT(EMPLOYEE_ID, SCHOOL_ID,SCHOOL_YEAR_ID) SELECT e.EMPLOYEE_ID, b.OKVD, (SELECT s.id FROM minoas..MINOAS_SCHOOL_YEAR s WHERE s.IS_CURRENT_YEAR=1) FROM minoas..MINOAS_EMPLOYEE e INNER JOIN mkdb..basiko b on e.LEGACY_CODE COLLATE DATABASE_DEFAULT
=b.KVD COLLATE DATABASE_DEFAULT

INSERT minoas..MINOAS_EMPLOYEE_REGULAR(EMPLOYEE_ID,APPOINTMENT_GOF, APPOINTMENT_GOF_DATE, REGISTRY_ID) SELECT e.EMPLOYEE_ID, b.FEK, b.DFEK, b.AM FROM  minoas..MINOAS_EMPLOYEE e INNER JOIN mkdb..basiko b on e.LEGACY_CODE COLLATE DATABASE_DEFAULT
=b.KVD COLLATE DATABASE_DEFAULT


SELECT * FROM minoas..MINOAS_EMPLOYEE_REGULAR


INSERT minoas..MINOAS_EMPLOYMENT_REGULAR SELECT e.EMPLOYMENT_ID, (SELECT 10), NULL, NULL, NULL FROM minoas..MINOAS_EMPLOYMENT e


    SELECT u.UNIT_ID, u.TITLE FROM minoas..UNIT AS u
        INNER JOIN minoas..SCHOOL AS s ON u.UNIT_ID=s.UNIT_ID
        WHERE (u.TITLE LIKE '%Γρ%' OR u.TITLE LIKE '%ΘΜΙΑΣ%')
        ORDER BY u.TITLE


SELECT * FROM SECONDMENT

DELETE FROM SECONDMENT
UPDATE SECONDMENT SET IS_ACTIVE=0 WHERE EMPLOYEE_ID=3068 

UPDATE EMPLOYMENT  SET SECONDMENT_ID=NULL WHERE ID=6544

SELECT * FROM minoas..MINOAS_UNIT
SELECT * FROM minoas..MINOAS_SCHOOL
SELECT * FROM minoas..MINOAS_SCHOOL_YEAR
SELECT * FROM minoas..MINOAS_EMPLOYEE
SELECT * FROM minoas..MINOAS_EMPLOYEE_REGULAR
SELECT * FROM minoas..MINOAS_EMPLOYEE_DEPUTY

SELECT * FROM minoas..MINOAS_EMPLOYMENT AS e
    INNER JOIN minoas..MINOAS_EMPLOYMENT_DEPUTY AS em on e.EMPLOYMENT_ID=em.EMPLOYMENT_ID 


SELECT * FROM minoas..MINOAS_EMPLOYMENT_REGULAR
SELECT * FROM minoas..MINOAS_EMPLOYMENT_DEPUTY
DELETE FROM minoas..MINOAS_EMPLOYEE
DELETE FROM minoas..MINOAS_EMPLOYEE_REGULAR



DELETE FROM minoas..MINOAS_EMPLOYEE_REGULAR

DELETE FROM minoas..MINOAS_EMPLOYMENT_HPAID
DELETE FROM minoas..MINOAS_EMPLOYMENT_DEPUTY
DELETE FROM minoas..MINOAS_EMPLOYMENT_REGULAR


DELETE FROM minoas..MINOAS_EMPLOYEE_HPAID
DELETE FROM minoas..MINOAS_EMPLOYEE_DEPUTY
DELETE FROM minoas..MINOAS_EMPLOYEE_REGULAR

UPDATE minoas..EMPLOYEE SET CURRENT_EMPLOYMENT_ID=NULL
DELETE FROM minoas..REGULAR_EMPLOYEE_INFO
DELETE FROM minoas..EMPLOYMENT
DELETE FROM minoas..EMPLOYEE


SELECT * FROM EMPLOYEE e WHERE e.LAST_NAME LIKE '%ΦΟΥΚΑΔ%'
SELECT * FROM 

SELECT * FROM EMPLOYEE

UPDATE EMPLOYEE SET LAST_SPECIALIZATION_ID='ΠΕ0101' WHERE ID=9375
UPDATE EMPLOYEE SET VERSION=1 WHERE ID=9375
DELETE FROM EMPLOYEE  WHERE ID=9375



SELECT e.LAST_NAME, e.FIRST_NAME, e.LAST_SPECIALIZATION_ID, u.TITLE, l.DUE_TO, l.LEAVE_TYPE FROM EMPLOYEE_LEAVE l 
    INNER JOIN EMPLOYEE e ON e.ID=l.EMPLOYEE_ID
    INNER JOIN EMPLOYMENT em ON em.EMPLOYEE_ID=e.ID
    INNER JOIN UNIT u ON em.SCHOOL_ID=u.UNIT_ID
WHERE l.IS_ACTIVE=1 AND l.DUE_TO > '20091201' AND l.DUE_TO < '20091230'
ORDER BY  e.LAST_SPECIALIZATION_ID


;
; ΑΔΕΙΕΣ ΕΚΠΑΙΔΕΥΤΙΚΩΝ ΑΝΑ ΕΙΔΗΚΟΤΗΤΑ 
;

SELECT e.LAST_SPECIALIZATION_ID, COUNT(e.LAST_NAME) AS 'ΣΥΝΟΛΟ ΑΔΕΙΩΝ' FROM EMPLOYEE_LEAVE l 
    INNER JOIN EMPLOYEE e ON e.ID=l.EMPLOYEE_ID
    INNER JOIN EMPLOYMENT em ON em.EMPLOYEE_ID=e.ID
    INNER JOIN UNIT u ON em.SCHOOL_ID=u.UNIT_ID
    INNER JOIN SPECIALIZATION sp ON e.LAST_SPECIALIZATION_ID=sp.SPECIALIZATION_ID
    INNER JOIN SCHOOL sc ON em.SCHOOL_ID=sc.UNIT_ID
WHERE l.IS_ACTIVE=1 AND sc.REGION='Β'  AND l.DUE_TO > '20100126'
GROUP BY e.LAST_SPECIALIZATION_ID ORDER BY e.LAST_SPECIALIZATION_ID

;
; ΑΔΕΙΕΣ ΕΚΠΑΙΔΕΥΤΙΚΩΝ ΑΝΑ ΕΙΔΗΚΟΤΗΤΑ KAI TYPO
;

SELECT e.LAST_SPECIALIZATION_ID, COUNT(e.LAST_NAME) AS 'ΣΥΝΟΛΟ ΑΔΕΙΩΝ' FROM EMPLOYEE_LEAVE l 
    INNER JOIN EMPLOYEE e ON e.ID=l.EMPLOYEE_ID
    INNER JOIN EMPLOYMENT em ON em.EMPLOYEE_ID=e.ID
    INNER JOIN UNIT u ON em.SCHOOL_ID=u.UNIT_ID
    INNER JOIN SPECIALIZATION sp ON e.LAST_SPECIALIZATION_ID=sp.SPECIALIZATION_ID
    INNER JOIN SCHOOL sc ON em.SCHOOL_ID=sc.UNIT_ID
WHERE l.IS_ACTIVE=1 AND sc.REGION='Β'  AND l.DUE_TO > '20100126' AND em.EMPLOYMENT_TYPE='REGULAR'
GROUP BY e.LAST_SPECIALIZATION_ID ORDER BY e.LAST_SPECIALIZATION_ID











SELECT * FROM SPECIALIZATION s WHERE s.TITLE LIKE '%ΙΑΤΡ%'

SELECT * FROM UNIT u WHERE u.TITLE LIKE '%ΕΣΠΕΡΙΝΟ%' 



 
go