select * from RANK_INFO where LAST_RANK_DATE > '20130101' and LAST_RANK_DATE < '20131101'

select e.LAST_NAME, e.FIRST_NAME, e.FATHER_NAME, r.RANK, r.SALARY_GRADE , r.LAST_SALARY_GRADE_DATE
from EMPLOYEE e, EMPLOYEE_INFO ei, RANK_INFO r
where e.ID=ei.EMPLOYEE_ID and ei.CURRENT_RANK_INFO_ID = r.ID
and r.INSERTED_ON > '20130801' and r.INSERTED_ON < '20130901'
order by YEAR(r.LAST_SALARY_GRADE_DATE) asc, MONTH(r.LAST_SALARY_GRADE_DATE) asc, DAY(r.LAST_SALARY_GRADE_DATE) asc, e.LAST_NAME asc, e.FIRST_NAME asc