SELECT * FROM EMPLOYEE e WHERE e.LAST_NAME LIKE '%ΘΥΡΗ%' 
    ORDER BY e.LAST_NAME


SELECT * FROM EMPLOYMENT em WHERE em.EMPLOYEE_ID=10192

SELECT * FROM DISPOSAL d WHERE d.EMPLOYEE_ID=10192

SELECT * FROM SECONDMENT s WHERE s.EMPLOYEE_ID=10192

SELECT * FROM SERVICE_ALLOCATION s WHERE s.EMPLOYEE_ID=10192

SELECT * FROM UNIT WHERE UNIT_ID='202'




SELECT * FROM AUDIT WHERE AUDIT_COMMENT LIKE '%ΚΟΡΝΑΡΑΚΗΣ%'
