SELECT * FROM afm_am


SELECT a.afm FROM EMPLOYEE e 
    INNER JOIN REGULAR_EMPLOYEE_INFO ri ON ri.EMPLOYEE_ID=e.ID
    INNER JOIN afm_am a ON a.am=ri.REGISTRY_ID
WHERE e.IS_ACTIVE=1 

SELECT e.ID, e.LAST_NAME, e.VAT_NUMBER FROM EMPLOYEE e 
    INNER JOIN REGULAR_EMPLOYEE_INFO ri ON ri.EMPLOYEE_ID=e.ID
WHERE e.LAST_NAME='??????'
    AND e.IS_ACTIVE=1

BEGIN TRAN
UPDATE EMPLOYEE 
    SET VAT_NUMBER=(SELECT DISTINCT a.afm FROM EMPLOYEE e 
    INNER JOIN REGULAR_EMPLOYEE_INFO ri ON ri.EMPLOYEE_ID=e.ID
    INNER JOIN afm_am a ON a.am=ri.REGISTRY_ID
WHERE e.IS_ACTIVE=1 AND e.ID=EMPLOYEE.ID)

ROLLBACK TRAN

COMMIT TRAN


SELECT a.afm FROM EMPLOYEE e 
    INNER JOIN REGULAR_EMPLOYEE_INFO ri ON ri.EMPLOYEE_ID=e.ID
    INNER JOIN afm_am a ON a.am=ri.REGISTRY_ID
WHERE e.IS_ACTIVE=1 and e.ID=10939






