SELECT COUNT(*) FROM EMPLOYMENT WHERE ESTABLISHED_DATE IS NOT NULL

BEGIN TRANSACTION
UPDATE EMPLOYMENT 
SET ESTABLISHED_DATE=(SELECT APPOINTMENT_GOF_DATE FROM REGULAR_EMPLOYEE_INFO WHERE EMPLOYEE_ID=EMPLOYMENT.EMPLOYEE_ID)
WHERE EMPLOYMENT.ID IN(
SELECT em.ID FROM EMPLOYMENT em 
    INNER JOIN EMPLOYEE e ON em.EMPLOYEE_ID=e.ID    
WHERE em.ESTABLISHED_DATE IS NULL AND em.EMPLOYMENT_TYPE='REGULAR') 


COMMIT TRANSACTION
ROLLBACK TRANSACTION

SELECT * FROM REGULAR_EMPLOYEE_INFO

SELECT * FROM REGULAR_EMPLOYEE_INFO