BEGIN TRAN
DELETE EMPLOYEE_LEAVE

DROP TABLE EMPLOYEE_LEAVE

ALTER TABLE EMPLOYEE DROP COLUMN LEAVE_ID

ALTER TABLE EMPOYEE DROP CONTRAINT FK75C8D6AE4B1C6AAC

SELECT * FROM SCHOOL_YEAR

SELECT * FROM EMPLOYMENT em WHERE em.EMPLOYEE_ID=10659
SELECT * FROM EMPLOYEE e WHERE e.LAST_NAME LIKE '%ΠΑΧΙΑΔΑΚΗ%'

8492

SELECT * FROM SECONDMENT s WHERE s.EMPLOYEE_ID=8492
SELECT * FROM DISPOSAL d WHERE d.EMPLOYEE_ID=8492
SELECT * FROM SERVICE_ALLOCATION s WHERE s.EMPLOYEE_ID=8492

BEGIN TRAN
UPDATE EMPLOYMENT SET SECONDMENT_ID=NULL WHERE EMPLOYEE_ID=8492 AND AND SCHOOL_YEAR_ID=11
DELETE DISPOSAL WHERE EMPLOYEE_ID=8492 AND SCHOOL_YEAR_ID=11
DELETE SECONDMENT WHERE EMPLOYEE_ID=8492 AND SCHOOL_YEAR_ID=11

ROLLBACK TRAN

COMMIT TRAN