INSERT INTO SXOLEIA(KVDSX, KOD_SXOLEIOY, SXOLEIO, PERIOXH) VALUES('01','01', 'ΓΥΜ ΜΟΙΡΩΝ', 'Β')
INSERT INTO SXOLEIA(KVDSX, KOD_SXOLEIOY, SXOLEIO, PERIOXH) VALUES('02','02', 'ΛΥΚ ΜΟΙΡΩΝ', 'Β')
INSERT INTO SXOLEIA(KVDSX, KOD_SXOLEIOY, SXOLEIO, PERIOXH) VALUES('03','03', 'ΕΠΑΛ ΜΟΙΡΩΝ', 'Β')


INSERT INTO EIDIK(EID, PERIGRAFH) VALUES ('ΠΕ01', 'ΘΕΟΛΟΓΟΙ');
INSERT INTO EIDIK(EID, PERIGRAFH) VALUES ('ΠΕ02', 'ΦΙΛΟΛΟΓΟΙ');
INSERT INTO EIDIK(EID, PERIGRAFH) VALUES ('ΠΕ03', 'ΜΑΘΗΜΑΤΙΚΟΙ');
INSERT INTO EIDIK(EID, PERIGRAFH) VALUES ('ΠΕ04', 'ΦΥΣΙΚΟΙ');
INSERT INTO EIDIK(EID, PERIGRAFH) VALUES ('ΠΕ05', 'ΓΑΛΛΙΚΗΣ');
INSERT INTO EIDIK(EID, PERIGRAFH) VALUES ('ΠΕ06', 'ΑΓΓΛΙΚΗΣ');


